model_filename = "work_dirs/saved/model.pth"
dataloader_filename = "work_dirs/saved/dataset.pth"
GTbboxes_filename = "work_dirs/saved/GT_bboxes.pth"

model = "sdetr"
mode = "test" 
config_sdetr = "configs/submission/frozen_4/query_proj_value_proj.py"
checkpoint_sdetr = "work_dirs/checkpoints/query_proj_value_proj.pth"

skip_type = "NormalizeMultiviewImage"
eval = "mAP"
gpu_id = 1
launcher = "none"
fuse_conv_bn = false
tmpdir = "none"
gpu_collect = false
format_only = false
eval_options = "none"
out = "./show_results/sdetr.pkl"
show = true
show_dir = "./show_results"
