config = "configs/model.py"
checkpoint = "checkpoints/sdetr.pth"
eval = "mAP"
gpu_id = 1
launcher = "none"
fuse_conv_bn = false
tmpdir = "none"
gpu_collect = false
format_only = false
eval_options = "None"
out = "./show_results/sdetr.pkl"
show = true
show_dir = "./show_results"
