model = "sdetr"

config_detr3d = "detr3d/configs/detr3d/detr3d_res101_gridmask.py"
checkpoint_detr3d = "checkpoints/detr3d.pth"
config_sdetr = "configs/model.py"
checkpoint_sdetr = "checkpoints/sdetr.pth"

eval = "mAP"
gpu_id = 0
launcher = "none"
fuse_conv_bn = false
tmpdir = "none"
gpu_collect = false
format_only = false
eval_options = "none"
out = "./show_results/sdetr.pkl"
show = true
show_dir = "./show_results"
