model_filename = "work_dirs/model.pth"
dataloader_filename = "work_dirs/data_loader.pth"
GTbboxes_filename = "work_dirs/GT_bboxes.pth"
model = "sdetr"
mode = "test" 

config_detr3d = "detr3d/configs/detr3d/detr3d_res101_gridmask.py"
checkpoint_detr3d = "checkpoints/detr3d.pth"
config_sdetr1 = "configs/submission/frozen_4/query_proj_value_proj.py"
config_sdetr = "configs/model.py"
checkpoint_sdetr = "checkpoints/sdetr.pth"
checkpoint_sdetr1 = "work_dirs/model_train/epoch_23.pth"

skip_type = "NormalizeMultiviewImage"

eval = "mAP"
gpu_id = 1
launcher = "none"
fuse_conv_bn = false
tmpdir = "none"
gpu_collect = false
format_only = false
eval_options = "none"
out = "./show_results/sdetr.pkl"
show = true
show_dir = "./show_results"
