model_filename = "work_dirs/saved/model.pth"
dataset_filename = "work_dirs/saved/data_loader.pth"
GTbboxes_filename = "work_dirs/saved/GT_bboxes.pth"

config_sdetr = "configs/submission/frozen_4/query_proj_value_proj.py"
checkpoint_sdetr = "work_dirs/checkpoints/query_proj_value_proj.pth"